### PR TITLE
fix formatting

### PR DESCRIPTION
**Pull request by calster00**
Formatting fix, no logic changes.

### CODE REVIEW

**Review by SergeOlabin — APPROVED** [review]
cool!
did you use some command to do the formatting across the project?

if so, do you mind adding that command running on pre-push?

**Comment by calster00** [comment]
@SergeOlabin I ran `prettier-format:all` from our `package.json`. It's complicated to do this pre-push, since after formatting you would also need to automatically make new commit (or amend last one) to save changes before pushing. 
I can add pre-commit hook instead to format staged files. It's not costly operation and only takes a second.

**Review by calster00 — COMMENTED** [review]
@SergeOlabin I ran `prettier-format:all` from our `package.json`. It's complicated to do this pre-push, since after formatting you would also need to automatically make new commit (or amend last one) to save changes before pushing. 
I can add pre-commit hook instead to format staged files. It's not costly operation and only takes a second.

**Comment by SergeOlabin** [comment]
@calster00 Seems good to me!
but pls discuss on the next sync with the team to get their opinion also

**Pull request closed without merging**
